# Generated by Django 5.0.6 on 2024-07-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hangul', models.TextField()),
                ('english', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChallengeGroup',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenges', models.ManyToManyField(to='api.challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
