# Generated by Django 5.0.7 on 2024-07-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_typingspeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='active',
        ),
        migrations.RemoveField(
            model_name='challengegroup',
            name='active',
        ),
        migrations.RemoveField(
            model_name='typingspeed',
            name='active',
        ),
        migrations.AddField(
            model_name='challenge',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='challengegroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='typingspeed',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
